settings = {"win bg":"#d4d4d4",
            "pane bg":"#d4d4d4",
            "button bg":"#d4d4d4",
            "font color":"#000000",
            "font name":"Ariel",
            "padding x": 10,
            "padding y": 10,
            "font size": 12,
            "Title":"Germanna ACE Quick-Kopy",
            "icon":"icon.ico",
            }